defmodule Exclosured.RPC.TypeScript do
  @moduledoc """
  Generates TypeScript declaration files for annotated RPC exports.
  """

  @number_types ~w(u8 u16 u32 u64 i8 i16 i32 i64 usize isize f32 f64)
  @header """
  // Generated by Exclosured from annotated Rust RPC exports.
  // Do not edit by hand.
  """

  @doc """
  Generate a TypeScript declaration file from parsed RPC metadata.
  """
  def generate(rpcs, opts \\ []) when is_list(rpcs) do
    module_name =
      opts
      |> Keyword.get(:module_name, "ExclosuredWasmModule")
      |> validate_type_name!()

    source = Keyword.get(opts, :source)

    [
      String.trim_trailing(@header),
      source_comment(source),
      "",
      "export default function init(input?: RequestInfo | URL | Response | BufferSource | WebAssembly.Module): Promise<unknown>;",
      "",
      "export interface #{module_name} {",
      rpcs |> Enum.map(&interface_member/1) |> Enum.join("\n"),
      "}",
      "",
      rpcs |> Enum.map(&export_function/1) |> Enum.join("\n"),
      ""
    ]
    |> Enum.reject(&is_nil/1)
    |> Enum.join("\n")
  end

  @doc """
  Parse Rust source content and generate TypeScript declarations.
  """
  def generate_from_source(source, opts \\ []) when is_binary(source) do
    source
    |> Exclosured.RPC.Parser.parse()
    |> generate(opts)
  end

  defp source_comment(nil), do: nil
  defp source_comment(source), do: "// Source: #{source}"

  defp interface_member(rpc) do
    "  #{rpc.name}: #{function_type(rpc)};"
  end

  defp export_function(rpc) do
    "export function #{rpc.name}(#{typed_args(rpc.args)}): #{return_type(rpc)};"
  end

  defp function_type(rpc) do
    "(#{typed_args(rpc.args)}) => #{return_type(rpc)}"
  end

  defp typed_args(args) do
    args
    |> Enum.with_index(1)
    |> Enum.map(fn {arg, index} ->
      "#{argument_name(arg.name, index)}: #{type(arg.type)}"
    end)
    |> Enum.join(", ")
  end

  defp argument_name(name, index) do
    cond do
      valid_identifier?(name) and not reserved_word?(name) -> name
      true -> "arg#{index}"
    end
  end

  defp return_type(%{async: true, return: return_type}) do
    "Promise<#{return_value_type(return_type)}>"
  end

  defp return_type(%{return: return_type}) do
    return_value_type(return_type)
  end

  defp return_value_type(nil), do: "void"
  defp return_value_type(type), do: type(type)

  defp type(type) do
    type
    |> normalize_type()
    |> type_from_normalized()
  end

  defp normalize_type(type) do
    type
    |> String.trim()
    |> String.replace(~r/&'[A-Za-z_][A-Za-z0-9_]*\s+/, "&")
    |> String.replace(~r/\s+/, "")
  end

  defp type_from_normalized(type) when type in @number_types, do: "number"
  defp type_from_normalized("bool"), do: "boolean"
  defp type_from_normalized(type) when type in ~w(String str &str), do: "string"
  defp type_from_normalized(type) when type in ~w(&[u8] Vec<u8>), do: "Uint8Array"
  defp type_from_normalized("()"), do: "void"

  defp type_from_normalized("Vec<" <> rest) do
    inner = rest |> unwrap_generic() |> type_from_normalized()

    if String.contains?(inner, " | ") do
      "Array<#{inner}>"
    else
      "#{inner}[]"
    end
  end

  defp type_from_normalized("Option<" <> rest) do
    inner = rest |> unwrap_generic() |> type_from_normalized()
    "#{inner} | null"
  end

  defp type_from_normalized(_type), do: "unknown"

  defp unwrap_generic(type) do
    if String.ends_with?(type, ">") do
      String.slice(type, 0, String.length(type) - 1)
    else
      type
    end
  end

  defp valid_identifier?(name) do
    Regex.match?(~r/^[A-Za-z_$][A-Za-z0-9_$]*$/, name)
  end

  defp validate_type_name!(name) do
    if valid_identifier?(name) and not reserved_word?(name) do
      name
    else
      raise ArgumentError, "invalid TypeScript interface name: #{inspect(name)}"
    end
  end

  defp reserved_word?(name) do
    name in ~w(
      arguments await break case catch class const continue debugger default delete do else enum
      eval export extends false finally for function if implements import in instanceof interface
      let new null package private protected public return static super switch this throw true try
      type typeof var void while with yield
    )
  end
end
